### ISSUE TITLE
Sphere 0.56c pre-release

### ISSUE THREAD

**Issue by coruja747** [Sphereserver/Source#41]
This is an notice to devs and not really a issue, but since this thing automatically notify all devs on GIT it seems to be a nice place to post :P

some months ago we already tried to release 0.56c pre-release but devs had decided to postpone it until all current issues get fixed. Latest build (01 march 2016) seems to be stable, so maybe it's time to start the final tests

so if someone still have any pending commit, please commit it or wait until we move to 0.56d (just don't commit any buggy or non-tested changes, otherwise it will mess the final build). If also there's any bug left, just comment here or feel free to fix it

PS: there's no precise date to move, probably will take a few days or weeks, it will depend on how these latest builds will survive on final tests

**Comment by roberpot** [comment]
The 0.56c pre-release will be a new branch? We (Xun and me) are refactoring some code on a fork of the master branch to help new devs understand the code (and put some order on the sources...).

**Comment by coruja747** [comment]
honestly I don't know how it will be changed, probably the master branch will continue as 0.56d, and 0.56c will be moved to a new read-only branch (it doesn't really need to be writeable since there's no reason to continue sending commits after release the final version)

if it is just a small change or something really needed on 0.56c you can commit it without problems. But if it is a big change, I think it's better wait for 0.56d. Of course I'm not telling you to not commit, but we already postponed 0.56c since months ago and if we don't take a few to focus on tests instead commits, we will never be able to launch the final version :P

**Comment by nefthon** [comment]
We are working over my fork, so it will not be any problem ... everything will be merged at once, if we manage to succeed.

BTW i've been told on IRC that some 7x clients crashes on latest builds (7.0.47 doesnt crash) because of items being removed from layers (visually, they are still there) and from world. I can't figure it out, I don't have time for it either since my hands are full, but I'll tell that people to reply here so maybe you can find the problem, since it's something I think that should be fixed before moving on a new version.

**Comment by drk84** [comment]
Yes,  this happens in recent nightly builds ( alexpetro told me 27 january build was fine).

Pratically, while the items  actually exists,  they doesn't appear in the paperdoll nor in the player in the game window.  If you equip an item, the item appears in both paperdoll and in the game window, but when you log out and log in back the item  "disappears" again.  Sometime things goes really crazy and you get like a wall graphic in the ring slot and so on  (i think this causes the crashes).

I tested with client from 7.0.10.3 to 7.0.20  with  high sea expansion  installation.
I also tested with a Mondain legacy client and a Mondain Legacy installation, in this case, there were no problems. 
Maybe is something related to sphere reading the extended tiledata (because they extended it with the high sea expansion) ? Don't know 

Hasta la vista

**Comment by roberpot** [comment]
Why 0.56c will be a read only branch? If is stable release, and new bugs on that release are reported, then we have to fix on that branch (and on master too of course!).

**Comment by cbnolok** [comment]
Well, i would fix that EC buy issue first, and there are also some issues pending here on GIT, so i honestly would solve known bugs before moving on. Also i wouldn't waste time on fixing bugs on 0.56c once we moved on 0.56d, people should always use the new version, so my opinion is to keep 0.56c branch read-only.

**Comment by coruja747** [comment]
nah, I'm testing this pull request here on my local PC and now sphere crash at startup when loading mul files, also the buy packet still not working on enhanced clients :/

**Comment by cbnolok** [comment]
Maybe it's better to talk about this on the pull request itself, however i don't get any crash and the buy gump works with that UI, i have not said/checked if it worked with latest UI (and i didn't hope it did). Anyways, i think i have fixed in the latest commit on my branch what was the possible cause of your crash, so let me know if it works!

**Comment by coruja747** [comment]
yep it's working fine now. But although it works on all CC and some old/modified EC, it still had the old problem: doesn't working correctly on all EC. I'm quite sure we're missing something, because RunUO doesn't even have support to EC and the buy menu works perfectly on all CC/EC using old packets.
But anyway I already wasted too many time trying to make it work, but still not working. So I give up, maybe we will only have a working EC buy menu on 56d :P

so is there any other bug left to fix?

**Comment by cbnolok** [comment]
Were #43, #25 and #18 solved? Also, i would wait for #29.

**Comment by coruja747** [comment]
#18: fixed
#25: can't reproduce it here
#29: its just a minor issue, there's no problem fix it later
#43: crash problem is fixed / hue problem not fixable

so maybe all major/crash problems was fixed, is there something left?

**Comment by cbnolok** [comment]
There's #49 now, but when it will be closed i'll be okay with a new prerelease. Actually, i would wait for the last fork changes to be done (1 week? Should ask to @nefthon), then do a 56c prerelease and pull the fork to the official repo to use it as a new master, beginning with 56d (even if, i would start with a new versioning style, we can discuss here).

**Comment by nefthon** [comment]
I think that it will be a good idea to rename current to 56c-PreRelease and send to it MAYOR bug fixes (crashes and so) only, while continuing working on latest build (AKA Nightly) as we've always done.

I'll explain the reason: Sometimes new bugs appears as we keep updating the source, and some people need stable releases for their live servers, but using as example last 56b pre-release they couldn't use it with newer clients since some packets changed and clients crashed when receiving the 'New Mobile Packet'. 

This way we can send that important fixes so they have it updated and we can focus on our job like always, but updating releases more often, 2 years between releases is NOT good.

As for the bugs, there are only a few ones left (that I'm aware of):
 - On old times, when Player A attacker Player B (both with blue noto), Player A was grey to Player B only, so Player B could decide wether to call guards and make Player A criminal to everyone or to kill him, or to leave it alone. Now Player A becomes criminal instantly.
 - Player A have a Pet and Player B attacks this pet, when Pet attacks back Player B, Player A becomes criminal.

I would move to 56d today, to do not last it longer, and then apply the fixes on both builds. We have our revamp done, so I'm waiting for 56d to apply the changes on it instead of the current 56c. If anyone have a word, I'll do it this night.

**Comment by coruja747** [comment]
although 56c is already usable on live servers (I always update my live server every week to latest build, and its totally stable/usable) I think it's a good idea. I will travel to another city today but I will send a pull request moving to 56d, if needed just click to merge it

**Comment by coruja747** [comment]
I acidentaly sent it as commit instead pull request lol
But I think we also must create the 56c branch on scripts
